# fly.toml app configuration file generated for weathered-snow-6428 on 2023-10-31T01:31:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-snow-6428"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
